"""
File: services.py
Description: FastAPI service endpoints for image registration and batch processing
Author: Arturo Gomez-Chavez
Creation Date: 30.06.2025
Institution/Organization: Constructor University GmbH
Contributors/Editors:
License: MIT License - See LICENSE.MD file for details
Contact & Support:
- Email: [support@example.com]
"""

from fastapi import APIRouter, HTTPException
from app.schemas import (
    ServiceResponse,
    FourierSoft2DResponse, 
    FourierSoft2DRequest, 
    ImageStitchingRequest,
    ImageStitchingResponse, 
    PlotRegistrationRequest,
    BatchFourierSoft2DRequest,
    BatchFourierSoft2DResponse,
    BatchImageStitchingRequest,
    BatchImageStitchingResponse
)
from app.services.executor import WorkspaceServiceExecutor
from app.services.batch_processor import BatchProcessor
from app.services.batch_stitching_processor import BatchStitchingProcessor

import logging

logger = logging.getLogger(__name__)
router = APIRouter()
executor = WorkspaceServiceExecutor()
batch_processor = BatchProcessor()
batch_stitching_processor = BatchStitchingProcessor()

@router.post("/fourier-soft2d", response_model=FourierSoft2DResponse)
async def run_fourier_soft2d(request: FourierSoft2DRequest):
    """
    Execute fourier_soft2D C++ program for image registration. 
    Computes and saves all most possible registration solutions.
    
    - **image1_path**: Path to first image | Relative to /input directory
    - **image2_path**: Path to second image | Relative to /input directory  
    - **output_dir**: [Optional] Output directory name | Relative to /output directory | DEFAULT: current UNIX timestamp
    - **dimensions**: [Optional] New image dimensions for re-scaling | Must be power of 2 | DEFAULT: auto-detect closest 2^n
    - **debug**: Enable debug mode | DEFAULT: false | Saves addition csv files wit intermediate results and necessary for 'plot-registration' service
    """
    logger.info(f"Executing Fourier Soft 2D with images: {request.image1_path}, {request.image2_path}")
    
    result = await executor.run_fourier_soft2d(request)
    
    if not result["success"]:
        raise HTTPException(status_code=500, detail=result)
    
    return FourierSoft2DResponse(**result)

@router.post("/plot-registration", response_model=ServiceResponse)
async def run_plot_registration(request: PlotRegistrationRequest):
    """
    Execute plotRegistrationSolution.py for plotting registration solutions from the fourier_soft2D output.\n
    This service generates plots based on the CSV files created by the fourier_soft2D service.\n
    It needs to run based on a CSV file generated by the fourier_soft2D service, named 'registration_solutions_transformation.csv'\n
    User could import it's own and follow the same format.
    
    - **folder_name**:  [Optional] Name of output | Relative to /output |
                        If not provided, uses folder with latest UNIX timestamp
    """
    folder_info = f" for folder: {request.folder_name}" if request.folder_name else " (latest folder)"
    logger.info(f"Executing Plot Registration Solution{folder_info}")
    
    result = await executor.run_plot_registration(request)
    
    if not result["success"]:
        raise HTTPException(status_code=500, detail=result)
    
    return ServiceResponse(**result)

@router.post("/image-stitching", response_model=ImageStitchingResponse)
async def run_image_stitching(request: ImageStitchingRequest):
    """
    Execute imageStitching.py for image stitching operations.\n
    The method applies the transformation from Image 1 to Image 2, unless inverse is set to true.\n
    **Output**: The stitched images: 'stitched_originals_blend.png' and 'stitched_colormaps_blend.png' are saved in the /output directory.
    If scaling is enabled, filenames include scaling suffix (e.g., 'stitched_originals_blend_scaled_0.500x0.500.png').

    - **image1_path**: Path to first image | Relative to /input directory
    - **image2_path**: Path to second image | Relative to /input directory
    - **override_inputdir**: [Optional] Flag to override relative input dir, and give full path to images | DEFAULT: false
    - **csv_dir_path**: [Optional] Path to directory containing CSV file
    - **subdir_output**: [Optional] Path to subdirectory to save the image file results
    - **solution_index**: [Optional] Solution index | DEFAULT: 0 | If the csv file has multiple solutions (row-based), this specifies which one to use
    - **inverse**: [Optional] Apply inverse transformation | DEFAULT: false | Transform img2 to align with img1 instead
    - **adjust_canvas**: [Optional] Adjust canvas size to fit full transformation | DEFAULT: false
    - **doscale**: [Optional] Enable scaling compensation | DEFAULT: false | Compensates for resolution differences between current images and those used for registration
    - **sx**: [Optional] Manual scaling factor in x direction | Used only when doscale=true | If not provided, automatically extracted from experiment_task_logs.csv
    - **sy**: [Optional] Manual scaling factor in y direction | Used only when doscale=true | If not provided, automatically extracted from experiment_task_logs.csv
    - **match_canvas**: Match canvas sizes when transform image has larger canvas (e.g., pre-stitched) | DEFAULT: false | When provided sx and sy must be set manually
    """

    logger.info(f"Executing Image Stitching with images: {request.image1_path}, {request.image2_path}")
    
    result = await executor.run_image_stitching(request)
    
    if not result["success"]:
        raise HTTPException(status_code=500, detail=result)
    
    return ImageStitchingResponse(**result)

@router.post("/batch-fourier-soft2d", response_model=BatchFourierSoft2DResponse)
async def run_batch_fourier_soft2d(request: BatchFourierSoft2DRequest):
    """
    Execute batch fourier_soft2D processing for sequential numbered image pairs with CSV merging.
    
    **Process Overview:**
    1. Detects numbered images matching the pattern (e.g., image_001.png, image_002.png)
    2. Creates sequential pairs: (image_001.png, image_002.png), (image_002.png, image_003.png), etc.
    3. Processes each pair through fourier_soft2D (debug=false, specified dimensions)
    4. Adds unique UUID to each pair's CSV files for experiment tracking
    5. Merges all registration_solutions_transformation.csv into batch_registration_solutions.csv
    6. Merges all experiment_task_logs.csv into batch_experiment_task_logs.csv
    7. Cleans up intermediate temporary directories
    
    **Output Structure:**
    ```
    /workspace/output/{output_dir}/
    ├── batch_registration_solutions.csv      # Merged registration results with UUIDs
    └── batch_experiment_task_logs.csv        # Merged experiment logs with UUIDs
    ```
    
    **UUID Integration:**
    - Each individual fourier_soft2D run gets a unique UUID
    - UUID is added as first column in both CSV files
    - Users can later join the two CSV files using the UUID column for detailed analysis
    
    **Example Request:**
    ```json
    {
        "input_directory": "my_experiment",
        "output_dir": "batch_experiment_1", 
        "base_pattern": "image_",
        "image_format": "png",
        "dimensions": 512,
        "start_index": 1,
        "end_index": 10
    }
    ```
    
    **Parameters:**
    - **input_directory**: Directory containing numbered images (relative to /workspace/input)
    - **output_dir**: Output directory name (created under /workspace/output)
    - **base_pattern**: Base name pattern (e.g., "image_", "frame_", "slice_")
    - **image_format**: Image file extension without dot (e.g., "png", "jpg", "tiff")
    - **dimensions**: Image dimensions for processing (REQUIRED - must be power of 2)
    - **start_index**: [Optional] Starting image index (auto-detected if not provided)
    - **end_index**: [Optional] Ending image index (auto-detected if not provided)
    - **max_concurrent**: Maximum concurrent processes (default: 3)
    
    **Note:** All individual fourier_soft2D processes run with debug=false for batch efficiency.
    """
    logger.info(f"Starting batch Fourier Soft 2D processing")
    logger.info(f"Input: {request.base_pattern}***.{request.image_format} in {request.input_directory}")
    logger.info(f"Output: /workspace/output/{request.output_dir}")
    logger.info(f"Dimensions: {request.dimensions}")
    
    result = await batch_processor.process_batch_fourier_soft2d(request)
    
    if not result["success"]:
        raise HTTPException(status_code=500, detail=result)
    
    return BatchFourierSoft2DResponse(**result)

@router.post("/batch-image-stitching", response_model=BatchImageStitchingResponse)
async def run_batch_image_stitching(request: BatchImageStitchingRequest):
    """
    Execute progressive batch image stitching using fourier registration results.
    
    **Progressive Stitching Process:**
    1. Loads batch CSV files from fourier processing results
    2. Calculates scaling factors from original vs scaled image dimensions
    3. Stitches images progressively: img1+img2 → result1, result1+img3 → result2, etc.
    4. Uses registration solutions for each pair transformation
    5. Produces final combined image from entire sequence
    
    **Input Requirements:**
    - Directory must contain: `batch_experiment_task_logs.csv` and `batch_registration_solutions.csv`
    - These files are generated by the batch-fourier-soft2d service
    
    **Output Structure:**
    ```
    /workspace/output/{registration_solution_dir}/
    ├── debug/                                    # (if debug=true)
    │   ├── 001_iteration/
    │   │   ├── stitched_originals_blend.png
    │   │   └── stitched_colormaps_blend.png
    │   ├── 002_iteration/
    │   │   └── ...
    │   └── ...
    └── batch_registration_{first}_to_{last}_image_stitched.png  # Final result
    ```
    
    **Example Request:**
    ```json
    {
        "registration_solution_dir": "microscopy_batch_512px",
        "doscale": true,
        "inverse": false,
        "debug": false
    }
    ```
    
    **Parameters:**
    - **registration_solution_dir**: Directory containing batch fourier CSV results
    - **doscale**: [Optional] Use original image sizes (true) or scaled sizes (false) - Default: true
    - **inverse**: [Optional] Apply inverse transformation for all pairs - Default: false  
    - **debug**: [Optional] Keep intermediate debug files and folders - Default: false
    
    **Progressive Stitching Logic:**
    - **Iteration 1**: original_img1 + original_img2 → stitched_result1
    - **Iteration 2**: stitched_result1 + original_img3 → stitched_result2  
    - **Iteration 3**: stitched_result2 + original_img4 → stitched_result3
    - **...and so on**
    
    **Canvas Management:**
    - First pair: `match_canvas=false`, `adjust_canvas=true`
    - Subsequent pairs: `match_canvas=true`, `adjust_canvas=true`
    
    **Scaling Calculation:**
    - If `doscale=true`: sx = original_width/scaled_width, sy = original_height/scaled_height
    - If `doscale=false`: sx = 1.0, sy = 1.0
    - Calculated once from first row and applied to all iterations
    """
    logger.info(f"Starting progressive batch image stitching")
    logger.info(f"Registration dir: {request.registration_solution_dir}")
    logger.info(f"Settings: doscale={request.doscale}, inverse={request.inverse}, debug={request.debug}")
    
    result = await batch_stitching_processor.process_batch_image_stitching(request)
    
    if not result["success"]:
        raise HTTPException(status_code=500, detail=result)
    
    return BatchImageStitchingResponse(**result)

@router.get("/health")
async def check_workspace_health():
    """Check if all workspace executables and directories are accessible"""
    return executor.check_executables()