from fastapi import APIRouter, HTTPException
from app.schemas import (
    ServiceResponse,
    FourierSoft2DResponse, 
    FourierSoft2DRequest, 
    ImageStitchingRequest, 
    PlotRegistrationRequest
)
from app.services.executor import WorkspaceServiceExecutor
import logging

logger = logging.getLogger(__name__)
router = APIRouter()
executor = WorkspaceServiceExecutor()

@router.post("/fourier-soft2d", response_model=FourierSoft2DResponse)
async def run_fourier_soft2d(request: FourierSoft2DRequest):
    """
    Execute fourier_soft2D C++ program for image registration. 
    Computes and saves all most possible registration solutions.
    
    - **image1_path**: Path to first image | Relative to /input directory
    - **image2_path**: Path to second image | Relative to /input directory  
    - **output_dir**: [Optional] Output directory name | Relative to /output directory | DEFAULT: current UNIX timestamp
    - **dimensions**: [Optional] New image dimensions for re-scaling | Must be power of 2 | DEFAULT: auto-detect closest 2^n
    - **debug**: Enable debug mode | DEFAULT: false | Saves addition csv files wit intermediate results and necessary for 'plot-registration' service
    """
    logger.info(f"Executing Fourier Soft 2D with images: {request.image1_path}, {request.image2_path}")
    
    result = await executor.run_fourier_soft2d(request)
    
    if not result["success"]:
        raise HTTPException(status_code=500, detail=result)
    
    return FourierSoft2DResponse(**result)

@router.post("/plot-registration", response_model=ServiceResponse)
async def run_plot_registration(request: PlotRegistrationRequest):
    """
    Execute plotRegistrationSolution.py for plotting registration solutions from the fourier_soft2D output.\n
    This service generates plots based on the CSV files created by the fourier_soft2D service.\n
    If it needs to be run based on a CSV file not generated by the fourier_soft2D service, name it 'registration_solutions_transformation.csv'\n
    and follow the format of the CSV file generated by the fourier_soft2D service.
    
    - **folder_name**:  [Optional] Name of output | Relative to /output |
                        If not provided, uses folder with latest UNIX timestamp
    """
    folder_info = f" for folder: {request.folder_name}" if request.folder_name else " (latest folder)"
    logger.info(f"Executing Plot Registration Solution{folder_info}")
    
    result = await executor.run_plot_registration(request)
    
    if not result["success"]:
        raise HTTPException(status_code=500, detail=result)
    
    return ServiceResponse(**result)

@router.post("/image-stitching", response_model=ServiceResponse)
async def run_image_stitching(request: ImageStitchingRequest):
    """
    Execute imageStitching.py for image stitching operations.
    The method applies the transformation from Image 1 to Image 2, unless inverse is set to true.
    **Output**: The stitched images: 'stitched_originals_blend.png' and 'stitched_colormaps_blend.png' are saved in the /output directory.
    If scaling is enabled, filenames include scaling suffix (e.g., 'stitched_originals_blend_scaled_0.500x0.500.png').

    - **image1_path**: Path to first image | Relative to /input directory
    - **image2_path**: Path to second image | Relative to /input directory
    - **csv_dir_path**: [Optional] Path to directory containing CSV file
    - **solution_index**: [Optional] Solution index | DEFAULT: 0 | If the csv file has multiple solutions (row-based), this specifies which one to use
    - **inverse**: [Optional] Apply inverse transformation | DEFAULT: false | Transform img2 to align with img1 instead
    - **adjust_canvas**: [Optional] Adjust canvas size to fit full transformation | DEFAULT: false
    - **doscale**: [Optional] Enable scaling compensation | DEFAULT: false | Compensates for resolution differences between current images and those used for registration
    - **sx**: [Optional] Manual scaling factor in x direction | Used only when doscale=true | If not provided, automatically extracted from experiment_task_logs.csv
    - **sy**: [Optional] Manual scaling factor in y direction | Used only when doscale=true | If not provided, automatically extracted from experiment_task_logs.csv
    """
    
    logger.info(f"Executing Image Stitching with images: {request.image1_path}, {request.image2_path}")
    
    result = await executor.run_image_stitching(request)
    
    if not result["success"]:
        raise HTTPException(status_code=500, detail=result)
    
    return ServiceResponse(**result)


@router.get("/health")
async def check_workspace_health():
    """Check if all workspace executables and directories are accessible"""
    return executor.check_executables()